/*
 * Singleton for GMap and utility functions.
 * @author: Maarten van Hoof
 * @copy: Edia 2007
 */
 
 var EMap = {
 	
 	/** The map itself. */
 	map: null,
	
	/** Map options: what the cursor looks like */
	mapOptions: {draggableCursor:"default", draggingCursor:"move"},

	/** The icons cached in an array. */
	icons: new Array(),
 	
	/** The types in an array, key = id, value = image. */
	markerTypes: new Array(),
	
	/** 
	 * In earlier versions, markerType.image referred to an actual icon image.
	 * We're still using these image names, but now they map to an icon color
	 * and the marker icons are generated by MapIconMaker.
	 */
	iconColors: {
		'img000.png': '#B5B5B5',
		'img001.png': '#C54030',
		'img002.png': '#DD4477',
		'img003.png': '#994499',
		'img004.png': '#6633DD',
		'img005.png': '#3B668F',
		'img006.png': '#3166CC',
		'img007.png': '#29A694',
		'img008.png': '#2E8E5E',
		'img009.png': '#139420',
		'img010.png': '#65A908',
		'img011.png': '#AAAA14',
		'img012.png': '#D4AE00',
		'img013.png': '#F28700',
		'img014.png': '#DE5415',
		'img015.png': '#A4736F',
		'img016.png': '#936E8F',
		'img017.png': '#627488',
		'img018.png': '#7581A9',
		'img019.png': '#5E8C89',
		'img020.png': '#8A8950',
		'img021.png': '#B08B57'
	},
	
	defaultIcon: "img001.png",
 	
 	init: function(mapDiv) {
 		EMap.map = new GMap2(mapDiv, EMap.mapOptions);
		EMap.map.setCenter(new GLatLng(23.563987128451217, 10.8984375), 2);
		EMap.map.addControl(new GLargeMapControl());
		EMap.map.addControl(new GMapTypeControl());
 	},
 	
 	getInfoWindow : function() {
		return EMap.map.getInfoWindow();
 	},
 	/**
	 * Get the marker icon for the given marker type ans zoom level.
	 */
	getIcon : function(typeId, zoomLevel) {
 		// Get the marker type
		var markerType;
 		if (typeId) {
 			markerType = EMap.markerTypes[typeId];
 		}
		// get the image
 		var image;
 		if (markerType) {
 			image = markerType.image;
 		}
		// Find out if we've already created this icon
 		var icon;
		if (image) {
			icon = EMap.icons[image+zoomLevel];
		}
 		if (icon == null) {
			// we haven't. Create it.
			var size = 14;
			if (zoomLevel)
				size += (zoomLevel*2);
			else 
				size += (EMap.map.getZoom()*2);
			var color;
			if (image)
				color = EMap.iconColors["img"+image];
			else
				color = EMap.iconColors[EMap.defaultIcon];
			
			var icon = MapIconMaker.createMarkerIcon({width: size, height: size, primaryColor: color, cornerColor: color});
			
			// Store this icon for future use.
			EMap.icons[image+zoomLevel] = icon;
 		}
 		// return the icon
 		return icon;
 	},
 	registerMarkerType : function(id, image, name) {
 		EMap.markerTypes[id] = new EMap.MarkerType(id, image, name);
 	},
 	MarkerType : function(id, image, name) {
		this.id = id;
		this.image = image;
		this.name = name;
	}
};